version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MemoriesTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cqgy7l58hxc7"
s3_prefix = "MemoriesTest"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
