name: Posts Stack Python Tests

on:
  push:
    branches: [master]
    paths: ['aws/src/posts/**']
  pull_request:
    branches: [master]
    paths: ['aws/src/posts/**']

jobs:
  test-auth-stack:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: aws/src/posts/tests
      - name: Run unit tests
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          python -m unittest discover -s . -p "test_*.py"
        working-directory: aws/src/posts/tests
